dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- export TZ=Brazil/East
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
deploy:
  provider: heroku
  api_key:
    secure: ZfDhAbIKpC72Aueivgh75K+2Z/WknGS/gya8V6A0JV/K5MhzZiX5A4nE9SQtTYdyDJnlu7FV/+6bdAdQ1PEaZ2kqPT9aQk00iXEDgJlOOP9Ibqxsb+4XjoeOQZEgF559wgRqcwqgMvejvtxvUdeHXw/EAWfe6H2RfamWZGTA7saYduTubBk7uubZ+BImZpwvntJtj0Yn5bglUhpNnaiAn0eYHyAF7IL8dS0OiZK/zC+1prL0WDSA8HzvWiXp9jQ2nyTLYPBaI/udVHRXAy2k/oUqkRCXVporJ4d8iFv6xEKFbjR5Tkc2BZxDYnqyEmDUz04eNgI2dfcXMOI9aYFm8yD8unpfLUNJ0uaSLHRPX0DJJ7lPJR8TssR01WayN3TM4uXdU73V0PA74sH68LCZurGe/0RQ9Xs/7DmlWZfoBx9eTQsRrgQl3Qo4ESGGDZHHvZxAulXqxH6xJrpGKAiAIQMjGNzwvnfmAzo7phsVrf73dBXqHZEm5fJi9A2uLAg7sQZgR2R0nJrWQKfiP41WGw8XNoNW/oJtzHrhR3SzuimlW/QQP6Z3aiuhO6fol1c+pfr4N3gFMJERAozRctsEIdzRDx4Cy9ihbgh09qyqM5+kvx4r8GECmxZ9TAO3o9A1FgZK5Fr5mF1XNVI4pfR7O4bbXcBCsKG6/VhaXxlQgDE=
  app: d-wallet-api
