dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- export TZ=Brazil/East
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
deploy:
  provider: heroku
  api_key:
    secure: WcaP2Bnty0+MBPi4Nj8TRjR+VMxQ0S5anPP/Z3QWhm4Fs1OfkiuMo+V0NuzURyYcmrGZWnlTSeJf2z7kPa4JOgfLQCv1+IRZNf+y4rU13C5sq+JdRwwlGrLplwRJWKLYF4jxKpBBTY2Qf87tG74+MUEaWSXgUX17YtWPKj62nq6783vpEo19Ramtp+ApWLFioPaDmE9Z2bbWgtO5KmWINbSat+TiGO3JCbHSBpy5JPmHOXmf+ZQtZsbNCrc+i6Oa9ASuh7tbAOYrmm5IkwCayt7AUh7QaK0QLRSA6DPlTxfk+tv9v2lCq8wzAVnrqVDTRqijh5YAtp/opPEa0Qo2wX0lC257Uzsv9ZRBviN8mPhqKCuwAeokNau5g/oAKuYAkI6J2m8VTLpTWCnSsmemY+DFoLaexZWlprWFcfPLCwjujrgEx1ohpbzHoNlkaC+DdjBADuk9cnlcCRZ+sNAD0XayPa7yYMVUM8CvGwMxDdny1hbI+GL/2hpqr0sDbjCitoht1HMNRHJ6Nm2djgc5AFV4cajH3wQfxi4s3yWtpCozDfgTxox2MWluMvO41SDXH6grr9gd3R66+IKaDvWPpE1eIdCf9GrGDhHcg4tHmlAoQ2/WLd5HD2/wNnHIebBQY61/7lbcVuH0iadNnF6b64B460jCibLFKOyOUIU/ExU=
  app: d-wallet-api
