dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: f77FUUW3HtC5p5wBgXMgtnqdHDiSzcQXJT8wuDboGe41hsHmZsVsrLiGhTEmIe/evj8WwCUBjzaFn8mx8TqzwYlNLrF0m1sOH15nLQRnsaCN1pWZbS+EJroS9l7w+3EnhBCwIOEhQ6lbL2JlNLSwbodOw/sz4WJ6pLVs/wUlaeahDDhE7U2EJLpwdlv+IrsN/PReAfED1ZY6z8Qb5sS6jq0CBOiVK8/6Do9KebrlpDBwEev+iFdpJin8wdmCNsgPvgtyr830XAWAuEzdFIJT1JJMzeAdVkVAwoHsWOvxz9RaEaU4KsiT9ckiBg/7HnRcc6uOewInl4YmnjVUfm+iWXVx7nA74qxQIuLfrRVOKZ5JQHFLzytP1mK5kGC9dfbrAGTdaK1FKUw4QHG2GGrneXS8jNBADsOvRsl4sgZ60+iRC9heh+IF5p/RTAjnxpc+J1j+/P/VS57YvF21aJsSlemSI9E7rA4pk96ylw40NHX9tpiSrgCPbzcsvwB6PonJUqqYGBpWgXy2PoFaJZYEHh4V5BzKebpnjzVsON4eh5AqB4pq8bUO6oopinowBBFSQKQ47EfFxldK1bSkwFqRSHhr2H8IpJkhJB5ynp9PT/R0xCILznXEI3PIP8J41eIjYuUfHpNKBGnFR+uf/J0/YbbzLOQ4/ye/5olP89eL2l8=
  app: d-wallet-api
