dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - export TZ=Brazil/East
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
deploy:
  provider: heroku
  api_key:
    - secure: 7b96787c-6d37-48cc-ad99-d408c9f9e193
  app: d-wallet-api