dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- export TZ=Brazil/East
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
deploy:
  provider: heroku
  api_key:
    secure: lgCky809Rv5JGbBJj8CN4D0KZSSalnLHiiAGAU8aC+gtuagk/fXEenCHm+wLc5JL/+oeQuHJ4hBTqLvWLQP4A8JYFgNtGC+Khr9LWyGrqZ2NADQMvmwms10xCwBlYXvcILnnUpos5LbZFDrfCDTUB3w1SkcZD/jsWUnpqQYKA/3NNO2D80tsX6jyJKhizbIH2PimaQ9TJpIlXCXSzqUTdwyqPFytzZkicA1CQ9RyTJ+P8jADsDK7o1iff6Lzuas1w5DsmyrpPCUe5L2YA79c1J0Bky9S14dBBl9bosjrBylHUfmjEcGT9JIuzYNuv1dqViECONeAD6WIpx+HAazgyGwFfKCpU01UoI+FnFFZyKffeOwlqGM3rRlSIy5LgUg0G/kglNyb/hhmtDDUrpnODBQer8kGfSGV5Ab60q8aOCnpRXRXxs3eANSBS0d7zujWYxeBpZp1c5OMFdCasqgtamTR46JvNxKwZXc5P6ZMUn6VhRIWWYSs+YTKw5LK26fFCGbqti/oCNxsGzC1BCZWINUd1pxOGIh9BL3Be8f+LY6Lj/drRTg1hUJlfP4YoWZyEcPcf+Ial59DDj2YBOkJIBdGS4I+01MKNT+T/4hg6+qSaZCxY1xpjHZMvnO4zzO9nmQFPyddSQ/lUx28Jr5lbf6E828xCUccG+Lbo7jE4i4=
  app: d-wallet-api
